var product = [{
    "id": 0,
    "title":"",
    "description": "",
    "brand": "",
    "image":"https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-picture-coming-creative-vector-png-image_40968940.jpg",
}, {
    "id": 1,
    "title":"Samsung Galaxy S24 Ultra 5G AI",
    "price": "1,14,999",
    "description": "Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Black, 12GB RAM, 512GB Storage",
    "brand": "Samsung",
    "image":"https://f.media-amazon.com/images/I/71Nwtop9jtL._AC_UY327_FMwebp_QL65_.jpg",
}, {
    "id": 2,
    "title":"Samsung Galaxy S25 Ultra 5G AI",
    "price":"1,29,999",
    "description": "Samsung Galaxy S25 Ultra 5G AI Smartphone (Titanium Whitesilver, 12GB RAM, 256GB Storage",
    "brand": "Samsung",
    "image":"https://m.media-amazon.com/images/I/71-d7XDbhIL.AC_UL320.jpg",
}, {
    "id": 3,
    "title":"iPhone 16 Pro",
    "description": "iPhone 16 Pro 512 GB: 5G Mobile Phone with Camera Control, 4k 120fps Dolby Vision and a Huge Leap in Battery Life. Works with Airpods; Black Titanium",
    "price":"1,42,900",
    "brand": "Apple",
    "image":"https://m.media-amazon.com/images/I/61Ony8rgwEL.AC_UY218.jpg",
}, {
    "id": 4,
    "title":"iPhone 16 PRO MAX 256 GB",
    "description": "iPhone 16 Pro Max 256 GB: 5G Mobile Phone with Camera Control, 4K 120fps Dolby Vision and a Huge Leap in Battery Life. Works with AirPods;Black Titanium",
    "price":"1,35,900",
    "brand": "Apple",
    "image":"https://m.media-amazon.com/images/I/619oqSJVY5L.AC_UY218.jpg",
}, {
    "id": 5,
    "title":"iQOO Neo 10R",
    "description": "iQOO Neo 10R 5G (MoonKnight Titanium, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery  Smartphone | Segement's Most Stable 90FPS for 5 Hours",
    "price":"28,998",
    "brand": "iQOO",
    "image":"https://m.media-amazon.com/images/I/610NUM9jlxL.AC_UY218.jpg",
}, {
    "id": 6,
    "title":"iQOO Z10 5G",
    "description": "iQOO Z10 5G (Stellar Black, 8GB RAM, 256GB Storage) | India's Biggest Ever 7300 mAh Battery | Snapdragon 7s Gen 3 Processor | Brightest Quad Curved AMOLED Display in The Segment",
    "price":"23,998",
    "brand": "iQOO",
    "image":"https://m.media-amazon.com/images/I/61-EXn6sLSL.AC_UY218.jpg",
}, {
    "id": 7,
    "title":"Oppo F27 Pro+ 5G",
    "description": "Opoo F27 Pro+ 5G(Midnight Navy, 8GB RAM, 256GB Storage) | 6.7 FHD+ AMOLED Toughest 3D Curved Display|64MP AI Featured Camera|Ip69| 67W SUPERVOOC| ",
    "price":"23,999",
    "brand": "Oppo",
    "image":"https://m.media-amazon.com/images/I/91wPh6RMcdL.AC_UY218.jpg",
}, {
    "id": 8,
    "title":"OPPO A5 PRO 5G",
    "description": "OPPO A5 PRO 5G (MOCHA Brown, 8GB RAM , 128GB Storage)|6.67 HD+ 120Hz Refresh Rate Screen | 45W SUPERVOOC| ",
    "price":"17,999",
    "brand": "Oppo",
    "image":"https://m.media-amazon.com/images/I/71juxOXVdrL.AC_UY218.jpg",
}, {
    "id": 9,
    "title":"Motorola razr 60 Ultra",
    "description": "Motorola razr 60 Ultra (Pantone Scarab, 16 GB RAM, 512 GB Storage) | Moto AI | Snapdragon 8 Elite Mobile Platform | 6.9 AMOLED 165Hz Display | 50 MP + 50 MP + 50 MP Triple Camera",
    "price":"99,999",
    "brand": "Motorola",
    "image":"https://m.media-amazon.com/images/I/51RIJoVuMhL.AC_UY218.jpg",
}, {
    "id": 10,
    "title":"Motorola razr 40",
    "description": "Motorola razr 40(Sage Green, 8GB RAM, 256GB Storage) | External AMOLED Display |6.9 AMOLED 144Hz Display | 64MP Main Camera | Android 13",
    "price":"44,990",
    "brand": "Motorola",
    "image":"https://m.media-amazon.com/images/I/61wp0d+7WGL.AC_UY218.jpg",
}];
